myblog/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  resources :posts
  resources :posts do
    resources :comments
  end
end

myblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

  

myblog/app/models/comment.rb
class Comment < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
    belongs_to :post
end

myblog/app/models/modules/wordcount.rb
module Wordcount
    def count_word
        self.body.length
    end
    
    def is_bad?(paragraph)
        paragraph=[is,body]
    end
end

myblog/app/models/post.rb
require 'modules/Wordcount'
class Post < ApplicationRecord
    include Wordcount
#    include badword
    validates :title, :body, :status, presence: true
    validates :title, length: { maximum: 50 }
    validates :body, length: { maximum: 200 }
    
    
    belongs_to :user
    has_many :post_tag_mappings
    has_many :tags, through: :post_tag_mappings
    has_many :comments , dependent: :destroy
    STATUS = {0 => "draft" , 1 => "publish", 2 => "archive"}
    
    scope :published, ->  { where(status: 1) }
    scope :drafts, ->  { where(status: 0) }
    scope :archives, ->  { where(status: 2) }
    
    
    before_create :assign_status
    def assign_status
        self.status = STATUS[0]
    end
    validate :check_bad, on: :save
    def check_bad
        puts check_bad
        errors.add(:title, "gives bad words") if is_bad
    end
    


end

myblog/app/models/post_tag_mapping.rb
class PostTagMapping < ApplicationRecord
    belongs_to :post
    belongs_to :tag
    
end

myblog/app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tag_mappings
    has_many :posts, through: :post_tag_mappings
end

myblog/app/models/user.rb
class User < ApplicationRecord
    validates :name, :email, :password, presence: true
    validates :email, uniqueness: true
    before_save :captialise_name
    
    def captialise_name
        self.name=self.name.capitalize
    end
    has_many :posts, dependent: :destroy
end

myblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
end

myblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /posts
  def index
    
      @post=Post.find(params["post_id"])
      puts params["post_id"]
      @commnets=@post.comments
    #render :json => @posts
  end

  # GET /posts/id
  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end
    
#  def create
#    comments = Comment.new(post_params)
#    if comments.save!
#      redirect_to posts_path, notice: "Post creation is successfull"
#    else
#      render :new
#    end
#  end
#    
#  def post_params
#    params.require(:).permit(:title, :body)
#  end
end

myblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  def index
    @posts = Post.all
    #render :json => @posts
  end

  # GET /posts/id
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save!
      redirect_to posts_path, notice: "Post was successfully created."
    else
      render :new
    end
  end
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

myblog/app/helpers/application_helper.rb
module ApplicationHelper
end

myblog/app/helpers/posts_helper.rb
module PostsHelper
end

myblog/app/views/Comments/index.html.erb
<% @comments.each do |comment| %>
    <div class="post">
      <h2><%= link_to comment.description, post_path(post) %></h2>

      <div class="date">
        <span class="glyphicon glyphicon-time"></span>
        <%= comment.created_at.strftime("%B %d, %Y") %>
      </div>


      <%= link_to "Read more &rarr;".html_safe, post_path(post) %>
    </div>

  <% end %>

myblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

myblog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post">
      <h2><%= link_to post.title, post_path(post) %></h2>

      <div class="date">
        <span class="glyphicon glyphicon-time"></span>
        <%= post.created_at.strftime("%B %d, %Y") %>
      </div>


      <%= link_to "Read more &rarr;".html_safe, post_path(post) %>
    </div>

  <% end %>

myblog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

myblog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>
<p>Created by User ID = <%= @post.user_id %></p>
<p>Published on Date : <%= @post.created_at %></p>